// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjghnwdtuoibqsgtugpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZ2hud2R0dW9pYnFzZ3R1Z3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTAxNDksImV4cCI6MjA2MzM4NjE0OX0.c_TZOsWvvcx-3BzCZeqb50FOPWTdw7m6TsNOxBqQqHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);